### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by Tertle950** [jakubtomsu/raylib-jump-prince#1]
Although the README states that this repository "could be a pretty good learning resource", it's technically unclear whether people are allowed to use it as such. As-is, [they legally can't](https://choosealicense.com/no-permission/).

I would add the [zlib license](https://github.com/raysan5/raylib/blob/master/LICENSE), which is what Raylib itself uses.

**Comment by jakubtomsu** [comment]
good point, I just added it
